[build]
  publish = ".next"
  command = "npm run build"

[functions]
  external_node_modules = ["jsdom"]
  node_bundler = "esbuild"
  
[[plugins]]
package = "@netlify/plugin-nextjs"

# Increase function timeout and memory
[functions."*"]
  included_files = ["utils/**"]
  memory = 1024
  timeout = 300
